import {
  ArrowUp,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  Car,
  Check,
  CircleHelp,
  ConciergeBell,
  CreditCard,
  Facebook,
  Globe2,
  HeartPulse,
  Image,
  Instagram,
  Mail,
  ListChecks,
  MapPin,
  MessageCircle,
  Search,
  ShieldCheck,
  Sparkles,
  Tv,
  Users,
  Utensils,
  Wifi,
  Wind,
} from 'lucide-react';
import type { DiscoveryAnswers, DiscoveryConfig, QuestionOption } from '../types/discovery';

const serviceOptions: readonly QuestionOption[] = [
  { value: 'wifi', label: 'Wi-Fi', icon: Wifi },
  { value: 'equipped-kitchen', label: 'Cocina equipada', icon: Utensils },
  { value: 'air-conditioning', label: 'Aire acondicionado', icon: Wind },
  { value: 'television', label: 'Televisión', icon: Tv },
  { value: 'parking', label: 'Parqueadero', icon: Car },
  { value: 'laundry', label: 'Lavandería', icon: Sparkles },
  { value: 'cleaning', label: 'Servicio de limpieza', icon: Sparkles },
  { value: 'reception', label: 'Recepción', icon: ConciergeBell },
  { value: 'security', label: 'Seguridad', icon: ShieldCheck },
  { value: 'elevator', label: 'Ascensor', icon: ArrowUp },
  { value: 'other', label: 'Otro', icon: CircleHelp },
];

const guestOptions: readonly QuestionOption[] = [
  { value: 'families', label: 'Familias', icon: Users },
  { value: 'business', label: 'Ejecutivos / viajeros de negocios', icon: Briefcase },
  { value: 'companies', label: 'Empresas', icon: Building2 },
  { value: 'tourists', label: 'Turistas', icon: MapPin },
  { value: 'foreigners', label: 'Extranjeros', icon: MapPin },
  { value: 'temporary', label: 'Personas que necesitan alojamiento temporal', icon: CalendarDays },
  { value: 'medical-family', label: 'Personas que vienen por motivos médicos o familiares', icon: HeartPulse },
  { value: 'other', label: 'Otros', icon: CircleHelp },
  { value: 'unsure', label: 'No estoy segura/o', icon: CircleHelp },
];

const capabilityOptions: readonly QuestionOption[] = [
  { value: 'photos-details', label: 'Ver fotografías y detalles de los apartamentos', icon: Image },
  { value: 'services', label: 'Conocer servicios e instalaciones', icon: Sparkles },
  { value: 'approximate-prices', label: 'Ver precios aproximados', icon: CreditCard },
  { value: 'dates', label: 'Seleccionar fechas de estadía', icon: CalendarDays },
  { value: 'availability', label: 'Consultar disponibilidad', icon: Search },
  { value: 'request-reservation', label: 'Solicitar una reserva', icon: Check },
  { value: 'quote', label: 'Solicitar una cotización', icon: Mail },
  { value: 'instant-booking', label: 'Reservar inmediatamente', icon: CalendarDays },
  { value: 'deposit', label: 'Pagar un anticipo', icon: CreditCard },
  { value: 'pay-stay', label: 'Pagar la estadía', icon: CreditCard },
  { value: 'whatsapp', label: 'Hablar por WhatsApp', icon: MessageCircle },
  { value: 'location', label: 'Consultar ubicación y cómo llegar', icon: MapPin },
];

const domainOptions: readonly QuestionOption[] = [
  {
    value: 'amoblados-santa-ines-com',
    label: 'amobladossantaines.com',
    icon: Building2,
  },
  {
    value: 'amoblado-santa-ines-com',
    label: 'amobladosantaines.com',
    icon: Building2,
  },
  {
    value: 'apartamentos-santa-ines-com',
    label: 'apartamentosantaines.com',
    icon: Building2,
  },
  {
    value: 'apartahotel-santa-ines-com',
    label: 'apartahotelsantaines.com',
    icon: Building2,
  },
  {
    value: 'santaines-apartamentos-com',
    label: 'santainesapartamentos.com',
    icon: Building2,
  },
  {
    value: 'santa-ines-barranquilla-com',
    label: 'santainesbarranquilla.com',
    icon: MapPin,
  },
  { value: 'santaines-com', label: 'santaines.com', icon: Globe2 },
  { value: 'santaines-co', label: 'santaines.co', icon: Globe2 },
  { value: 'santaines-com-co', label: 'santaines.com.co', icon: MapPin },
  { value: 'existing', label: 'Ya tenemos un dominio', icon: Globe2 },
  { value: 'other', label: 'Otra opción', icon: CircleHelp },
  { value: 'unsure', label: 'No estamos seguros todavía', icon: CircleHelp },
];

const reservationConditionOptions: readonly QuestionOption[] = [
  { value: 'cancellation', label: 'Política de cancelación', icon: ShieldCheck },
  { value: 'check-in-out', label: 'Horarios de entrada y salida', icon: CalendarDays },
  { value: 'deposit', label: 'Anticipo o depósito', icon: CreditCard },
  { value: 'rules', label: 'Reglas del apartamento', icon: ShieldCheck },
  { value: 'documents', label: 'Documentos o requisitos', icon: ListChecks },
  { value: 'included-services', label: 'Servicios incluidos o no incluidos', icon: Sparkles },
  { value: 'visitors', label: 'Reglas para visitantes', icon: Users },
  { value: 'not-defined', label: 'No tenemos políticas definidas todavía', icon: CircleHelp },
  { value: 'other', label: 'Otra', icon: CircleHelp },
];

export const santaInesConfig: DiscoveryConfig = {
  clientSlug: 'santa-ines',
  clientName: 'Santa Inés',
  logoPath: '/assets/logo.png',
  facadePath: '/assets/front.png',
  sections: [
    {
      id: 'apartments',
      label: 'Apartamentos',
      title: 'Primero, conozcamos los apartamentos',
      questions: [
        {
          id: 'totalApartments',
          type: 'number',
          label: '¿Cuántos apartamentos tienen disponibles actualmente?',
          summaryLabel: 'Total de apartamentos',
          helper: 'Puede ser un número aproximado.',
          placeholder: 'Ej. 12',
          required: true,
        },
        {
          id: 'apartmentDistribution',
          type: 'distribution',
          label: '¿Cómo se distribuyen?',
          summaryLabel: 'Distribución',
          helper: 'Registra cuántos apartamentos hay de cada tipo.',
          required: true,
        },
        {
          id: 'apartmentsSimilar',
          type: 'single',
          label: '¿Todos los apartamentos de una misma categoría son similares?',
          options: [
            { value: 'yes', label: 'Sí' },
            { value: 'no', label: 'No' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
        },
        {
          id: 'apartmentDifferences',
          type: 'textarea',
          label: '¿Cuáles son las principales diferencias?',
          placeholder: 'Por ejemplo: distribución, acabados, vista o equipamiento.',
          condition: (answers) => answers.apartmentsSimilar === 'no',
        },
        {
          id: 'apartmentOccupancy',
          type: 'occupancy',
          label: '¿Cuántas personas pueden alojarse aproximadamente en cada tipo?',
          summaryLabel: 'Capacidad aproximada',
          helper: 'Indica una aproximación o selecciona “No estoy segura/o”.',
          required: true,
        },
      ],
    },
    {
      id: 'services',
      label: 'Servicios',
      title: '¿Qué encuentra un huésped en Santa Inés?',
      questions: [
        {
          id: 'services',
          type: 'multi',
          label: 'Selecciona los servicios e instalaciones que están disponibles actualmente.',
          summaryLabel: 'Servicios disponibles',
          options: serviceOptions,
          otherField: {
            id: 'servicesOther',
            label: '¿Qué otro servicio?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'apartmentPhotos',
          type: 'multi',
          label: '¿Tienen fotografías actuales de los apartamentos?',
          summaryLabel: 'Fotografías actuales',
          options: [
            { value: 'professional', label: 'Sí, profesionales', icon: Camera },
            { value: 'phone', label: 'Sí, tomadas con celular', icon: Camera },
            { value: 'some', label: 'Tenemos algunas', icon: Image },
            { value: 'none', label: 'No', icon: CircleHelp },
            { value: 'unsure', label: 'Habría que revisarlo', icon: CircleHelp },
          ],
        },
      ],
    },
    {
      id: 'guests',
      label: 'Huéspedes',
      title: 'Conozcamos a sus huéspedes',
      questions: [
        {
          id: 'guestTypes',
          type: 'multi',
          label: '¿Qué tipo de huéspedes reciben normalmente?',
          options: guestOptions,
          otherField: {
            id: 'guestTypesOther',
            label: '¿Qué otro tipo de huésped?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'stayDurations',
          type: 'multi',
          label: '¿Cuánto suelen durar las estadías?',
          options: [
            { value: '1-3-days', label: '1–3 días' },
            { value: '4-7-days', label: '4–7 días' },
            { value: '1-4-weeks', label: '1–4 semanas' },
            { value: '1-3-months', label: '1–3 meses' },
            { value: 'over-3-months', label: 'Más de 3 meses' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
        },
        {
          id: 'receivesCompanyGuests',
          type: 'single',
          label: '¿Reciben actualmente huéspedes enviados o contratados directamente por empresas?',
          options: [
            { value: 'yes', label: 'Sí' },
            { value: 'no', label: 'No' },
            { value: 'occasionally', label: 'Ocasionalmente' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
        },
        {
          id: 'desiredGuest',
          type: 'textarea',
          label: '¿Qué tipo de huésped les gustaría atraer más?',
          helper: 'Si todavía no lo tienen claro, puedes escribir “No estoy segura/o”.',
          placeholder: 'Cuéntanos un poco sobre ese huésped ideal.',
          requiredMessage: 'Cuéntanos qué huésped les gustaría atraer, o escribe “No estoy segura/o”.',
        },
      ],
    },
    {
      id: 'stays',
      label: 'Estadías',
      title: 'Tarifas y estadías largas',
      questions: [
        {
          id: 'known-context',
          type: 'context',
          content: 'De nuestra conversación ya sabemos que las tarifas cambian según la temporada y que, en estadías mensuales, los servicios se cobran según el consumo real.',
        },
        {
          id: 'rateModels',
          type: 'multi',
          label: '¿Cómo manejan normalmente las tarifas?',
          options: [
            { value: 'night', label: 'Por noche' },
            { value: 'week', label: 'Por semana' },
            { value: 'month', label: 'Por mes' },
            { value: 'case-by-case', label: 'Se cotizan dependiendo del caso' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
        },
        {
          id: 'monthlyUtilities',
          type: 'multi',
          label: 'En estadías mensuales, ¿qué servicios paga el huésped aparte?',
          options: [
            { value: 'electricity', label: 'Energía' },
            { value: 'water', label: 'Agua' },
            { value: 'gas', label: 'Gas' },
            { value: 'internet', label: 'Internet' },
            { value: 'other', label: 'Otros' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
          otherField: {
            id: 'monthlyUtilitiesOther',
            label: '¿Qué otro servicio?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'hasUtilityBills',
          type: 'single',
          label: '¿Tienen acceso a facturas anteriores que nos permitan calcular rangos aproximados de consumo?',
          options: [
            { value: 'yes', label: 'Sí' },
            { value: 'no', label: 'No' },
            { value: 'review', label: 'Habría que revisarlo' },
          ],
          helper: 'Esto podría ayudarnos a mostrar rangos orientativos y evitar sorpresas para los huéspedes, especialmente con el consumo de energía. El valor final siempre dependería del consumo real.',
        },
      ],
    },
    {
      id: 'reservations',
      label: 'Reservas',
      title: '¿Cómo gestionan las reservas hoy?',
      questions: [
        {
          id: 'availabilityTracking',
          type: 'multi',
          label: 'Cuando alguien consulta por una estadía, ¿cómo verifican qué apartamentos están disponibles?',
          options: [
            { value: 'physical-agenda', label: 'Agenda física' },
            { value: 'excel', label: 'Excel' },
            { value: 'calendar', label: 'Calendario' },
            { value: 'whatsapp', label: 'WhatsApp' },
            { value: 'software', label: 'Software' },
            { value: 'memory-manual', label: 'De memoria / manualmente' },
            { value: 'other', label: 'Otro' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
          required: true,
          otherField: {
            id: 'availabilityTrackingOther',
            label: '¿Cuál otro método?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'availabilitySoftware',
          type: 'text',
          label: '¿Qué software utilizan?',
          placeholder: 'Nombre del software',
          condition: (answers) => answers.availabilityTracking.includes('software'),
        },
        {
          id: 'confirmedReservationTracking',
          type: 'multi',
          label: 'Cuando una reserva queda confirmada, ¿dónde la registran?',
          options: [
            { value: 'physical-agenda', label: 'Agenda física' },
            { value: 'excel', label: 'Excel' },
            { value: 'calendar', label: 'Calendario' },
            { value: 'whatsapp', label: 'WhatsApp' },
            { value: 'software', label: 'Software' },
            { value: 'other', label: 'Otro' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
          otherField: {
            id: 'confirmedReservationTrackingOther',
            label: '¿Cuál otro método?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'bookingInformation',
          type: 'textarea',
          label: '¿Qué información suelen pedirle al huésped antes de confirmar una reserva?',
          placeholder: 'Por ejemplo: nombres, fechas, número de personas o datos de contacto.',
          helper: 'Si depende del caso, puedes escribir “No aplica”.',
          requiredMessage: 'Cuéntanos qué información piden, o escribe “No aplica”.',
        },
        {
          id: 'reservationConditions',
          type: 'multi',
          label: '¿Qué condiciones debería conocer o aceptar un huésped antes de confirmar una reserva?',
          options: reservationConditionOptions,
          otherField: {
            id: 'reservationConditionsOther',
            label: '¿Qué otra condición?',
            placeholder: 'Escríbela aquí',
          },
        },
        {
          id: 'afterHours',
          type: 'multi',
          label: 'Si alguien se comunica fuera del horario de atención, ¿qué ocurre normalmente?',
          options: [
            { value: 'message', label: 'Deja un mensaje' },
            { value: 'whatsapp', label: 'Se responde por WhatsApp' },
            { value: 'next-hours', label: 'Se responde en el siguiente horario de atención' },
            { value: 'another-person', label: 'Otra persona atiende' },
            { value: 'case-by-case', label: 'Depende del caso' },
            { value: 'other', label: 'Otro' },
          ],
          otherField: {
            id: 'afterHoursOther',
            label: '¿Qué ocurre en ese caso?',
            placeholder: 'Una frase es suficiente',
          },
        },
        {
          id: 'reservationAuthority',
          type: 'multi',
          label: '¿Quién puede confirmar definitivamente una reserva?',
          options: [
            { value: 'reservations-manager', label: 'Encargado de reservas' },
            { value: 'administration', label: 'Administración' },
            { value: 'authorized-team', label: 'Cualquier miembro autorizado del equipo' },
            { value: 'other', label: 'Otro' },
          ],
          otherField: {
            id: 'reservationAuthorityOther',
            label: '¿Quién más puede confirmar una reserva?',
            placeholder: 'Escríbelo aquí',
          },
        },
      ],
    },
    {
      id: 'experience',
      label: 'Experiencia',
      title: 'Imaginemos la nueva experiencia de Santa Inés',
      description: 'Piensa en lo que haría más clara y cómoda la primera conversación con un huésped.',
      questions: [
        {
          id: 'desiredCapabilities',
          type: 'multi',
          label: '¿Qué te gustaría que pudiera hacer una persona desde la nueva página?',
          options: capabilityOptions,
          large: true,
          required: true,
        },
        {
          id: 'externalPlatforms',
          type: 'multi',
          label: '¿Les interesaría explorar presencia o reservas a través de otras plataformas?',
          options: [
            { value: 'booking', label: 'Booking.com' },
            { value: 'airbnb', label: 'Airbnb' },
            { value: 'expedia', label: 'Expedia' },
            { value: 'despegar', label: 'Despegar' },
            { value: 'other', label: 'Otra' },
            { value: 'not-now', label: 'No por ahora' },
            { value: 'unsure', label: 'No estamos seguros' },
          ],
          otherField: {
            id: 'externalPlatformsOther',
            label: '¿Cuál otra plataforma?',
            placeholder: 'Nombre de la plataforma',
          },
        },
        {
          id: 'domainPreference',
          type: 'multi',
          label: '¿Qué nombre de dominio quieren explorar para la nueva presencia digital de Santa Inés?',
          helper: 'Todas las opciones están sujetas a disponibilidad, precio y condiciones de compra. Son rutas iniciales, no una confirmación de registro; deben verificarse directamente con un registrador.',
          options: domainOptions,
          otherField: {
            id: 'domainOther',
            label: '¿Qué otra opción de dominio quieren explorar?',
            placeholder: 'Ej. santainesapartamentos.co',
          },
        },
        {
          id: 'existingDomain',
          type: 'text',
          label: '¿Cuál es el dominio que ya tienen?',
          helper: 'Escribe el dominio completo, por ejemplo: ejemplo.com.',
          placeholder: 'ejemplo.com',
          requiredMessage: 'Indica el dominio existente o escribe “No estoy segura/o”.',
          condition: (answers) => answers.domainPreference.includes('existing'),
        },
        {
          id: 'personalReview',
          type: 'single',
          label: 'Antes de confirmar una reserva, ¿prefieren revisarla personalmente?',
          options: [
            { value: 'yes', label: 'Sí' },
            { value: 'no', label: 'No' },
            { value: 'unsure', label: 'No estamos seguros todavía' },
          ],
        },
        {
          id: 'requestChannels',
          type: 'multi',
          label: '¿Dónde sería más cómodo recibir las nuevas solicitudes?',
          options: [
            { value: 'email', label: 'Correo electrónico', icon: Mail },
            { value: 'whatsapp', label: 'WhatsApp', icon: MessageCircle },
            { value: 'platform', label: 'Un panel dentro de la nueva plataforma', icon: Building2 },
            { value: 'unsure', label: 'No estamos seguros', icon: CircleHelp },
          ],
        },
        {
          id: 'requestEmail',
          type: 'text',
          inputType: 'email',
          label: '¿A qué correo electrónico prefieren recibir las nuevas solicitudes?',
          placeholder: 'correo@ejemplo.com',
          requiredMessage: 'Escribe un correo electrónico válido.',
          condition: (answers) => answers.requestChannels.includes('email'),
        },
      ],
    },
    {
      id: 'last-details',
      label: 'Últimos detalles',
      title: 'Pagos, imagen y objetivos',
      questions: [
        {
          id: 'deposit',
          type: 'single',
          label: '¿Solicitan actualmente algún anticipo para confirmar una reserva?',
          options: [
            { value: 'yes', label: 'Sí' },
            { value: 'no', label: 'No' },
            { value: 'depends', label: 'Depende de la estadía' },
          ],
        },
        {
          id: 'depositDetails',
          type: 'textarea',
          label: '¿Cómo lo manejan normalmente?',
          placeholder: 'Cuéntanos cuándo se solicita y cómo lo reciben.',
          condition: (answers) => answers.deposit === 'yes' || answers.deposit === 'depends',
        },
        {
          id: 'paymentMethods',
          type: 'multi',
          label: '¿Qué medios de pago reciben actualmente?',
          options: [
            { value: 'bank-transfer', label: 'Transferencia bancaria' },
            { value: 'nequi', label: 'Nequi' },
            { value: 'daviplata', label: 'Daviplata' },
            { value: 'card', label: 'Tarjeta débito/crédito' },
            { value: 'payment-link', label: 'Link de pago' },
            { value: 'cash', label: 'Efectivo' },
            { value: 'other', label: 'Otro' },
            { value: 'not-applicable', label: 'No aplica' },
            { value: 'unsure', label: 'No estoy segura/o' },
          ],
          otherField: {
            id: 'paymentMethodsOther',
            label: '¿Cuál otro medio de pago?',
            placeholder: 'Escríbelo aquí',
          },
        },
        {
          id: 'digital-presence',
          type: 'separator',
          label: 'Imagen y presencia digital',
        },
        {
          id: 'digitalImprovements',
          type: 'multi',
          label: 'Además de la página web, ¿qué les interesaría mejorar?',
          options: [
            { value: 'google-maps', label: 'Google / Google Maps', icon: Search },
            { value: 'facebook', label: 'Facebook', icon: Facebook },
            { value: 'instagram', label: 'Instagram', icon: Instagram },
            { value: 'professional-photos', label: 'Fotografías profesionales', icon: Camera },
            { value: 'visual-identity', label: 'Identidad visual', icon: Image },
            { value: 'advertising-material', label: 'Material publicitario', icon: Image },
            { value: 'seo', label: 'Posicionamiento en Google', icon: Search },
            { value: 'digital-ads', label: 'Publicidad digital', icon: MessageCircle },
            { value: 'unsure', label: 'No estamos seguros todavía', icon: CircleHelp },
          ],
        },
        {
          id: 'finalAdditionalNotes',
          type: 'textarea',
          label: '¿Hay algo más sobre Santa Inés que consideres importante que sepamos y que no hayamos preguntado?',
          helper: 'Si no hay nada adicional, puedes escribir “No”.',
          placeholder: 'Escribe una nota adicional o “No”.',
          rows: 5,
          secondary: true,
          requiredMessage: 'Cuéntanos algo más, o escribe “No”.',
        },
      ],
    },
  ],
};

export const initialAnswers: DiscoveryAnswers = {
  totalApartments: null,
  apartmentDistribution: { oneBedroom: 0, twoBedrooms: 0, threeBedrooms: 0 },
  apartmentsSimilar: '',
  apartmentDifferences: '',
  apartmentOccupancy: { oneBedroom: null, twoBedrooms: null, threeBedrooms: null },
  apartmentOccupancyUnknown: false,
  services: [],
  servicesOther: '',
  apartmentPhotos: [],
  guestTypes: [],
  guestTypesOther: '',
  stayDurations: [],
  receivesCompanyGuests: '',
  desiredGuest: '',
  rateModels: [],
  monthlyUtilities: [],
  monthlyUtilitiesOther: '',
  hasUtilityBills: '',
  availabilityTracking: [],
  availabilityTrackingOther: '',
  availabilitySoftware: '',
  confirmedReservationTracking: [],
  confirmedReservationTrackingOther: '',
  bookingInformation: '',
  reservationConditions: [],
  reservationConditionsOther: '',
  afterHours: [],
  afterHoursOther: '',
  reservationAuthority: [],
  reservationAuthorityOther: '',
  desiredCapabilities: [],
  externalPlatforms: [],
  externalPlatformsOther: '',
  domainPreference: [],
  domainOther: '',
  existingDomain: '',
  personalReview: '',
  requestChannels: [],
  requestEmail: '',
  deposit: '',
  depositDetails: '',
  paymentMethods: [],
  paymentMethodsOther: '',
  digitalImprovements: [],
  finalAdditionalNotes: '',
};
